name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-latest, windows-latest]
        emacs-version:
          - 27.2
          - 28.2
          - 29.4
        experimental: [false]
        include:
          - os: ubuntu-latest
            emacs-version: snapshot
            experimental: true
          - os: macos-latest
            emacs-version: snapshot
            experimental: true
          - os: windows-latest
            emacs-version: snapshot
            experimental: true
        exclude:
          - os: macos-latest
            emacs-version: 27.2
          - os: ubuntu-24.04-arm
            emacs-version: 27.2

    steps:
    - uses: actions/checkout@v3

    - uses: jcs090218/setup-emacs@master
      with:
        version: ${{ matrix.emacs-version }}

    - name: Setup Eask
      uses: emacs-eask/setup-eask@master
      if: matrix.os != 'ubuntu-24.04-arm'
      with:
        version: 'snapshot'
        architecture: 'x64'

    - name: Setup Eask for linux-aarch64
      uses: emacs-eask/setup-eask@master
      if: matrix.os == 'ubuntu-24.04-arm'
      with:
        version: 'snapshot'
        architecture: 'arm64'

    - name: Run tests
      run: 'make test'
